// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSW_Schedule_API.DbContexts;

#nullable disable

namespace PSW_Schedule_API.Migrations
{
    [DbContext(typeof(PSW_DbContext))]
    [Migration("20230308175311_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSW_Schedule_API.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Samantha"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Jin Ling"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Martha"
                        });
                });

            modelBuilder.Entity("PSW_Schedule_API.Models.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClientName = "XinGao",
                            EmployeeId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ClientName = "ChinLee",
                            EmployeeId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            ClientName = "Mathew",
                            EmployeeId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            ClientName = "Zamana",
                            EmployeeId = 3L
                        });
                });

            modelBuilder.Entity("PSW_Schedule_API.Models.Schedule", b =>
                {
                    b.HasOne("PSW_Schedule_API.Models.Employee", "Employee")
                        .WithMany("Schedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PSW_Schedule_API.Models.Employee", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
