// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSW_Schedule_API.DbContexts;

#nullable disable

namespace PSW_Schedule_API.Migrations
{
    [DbContext(typeof(PSW_DbContext))]
    partial class PSW_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSW_Schedule_API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Samantha"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jin Ling"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Martha"
                        });
                });

            modelBuilder.Entity("PSW_Schedule_API.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "XinGao",
                            EmployeeId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientName = "ChinLee",
                            EmployeeId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClientName = "Mathew",
                            EmployeeId = 2
                        },
                        new
                        {
                            Id = 4,
                            ClientName = "Zamana",
                            EmployeeId = 3
                        });
                });

            modelBuilder.Entity("PSW_Schedule_API.Models.Schedule", b =>
                {
                    b.HasOne("PSW_Schedule_API.Models.Employee", "Employee")
                        .WithMany("Schedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PSW_Schedule_API.Models.Employee", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
